name: CI

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        extensions: sqlite, pdo_sqlite

    - name: Install dependencies
      run: |
        composer install --no-interaction --prefer-dist --optimize-autoloader
        npm install
        npm run build
        
    - name: Run Phpstan
      run: vendor/bin/phpstan analyse app tests

    - name: Run Tests
      run: |
        cp .env.ci .env
        touch database/database.sqlite
        php artisan key:generate
        php artisan migrate
        php artisan test